name: eMPaPP CI CD

on: [push]

env:
  AZURE_WEBAPP_NAME: emp_app   # Application name in Azure
  NODE_VERSION: '18.x'         # Node.js version

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # Checkout the repository
    - name: 'Checkout GitHub Action' 
      uses: actions/checkout@v4  # Updated to latest stable version
   
    # Azure Login
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.SECRETREACT }}
        
    # Setup Node.js
    - name: Setup Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}

    # Install dependencies, build, and test
    - name: Install dependencies, build, and test
      run: |
        npm install
        npm run build --if-present
        npm run test --if-present
      working-directory: ./emp_app  # Set correct project folder
               
    # Deploy web app to Azure
    - name: Deploy to Azure
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ env.emp_app }}  # Fixed incorrect variable reference
        package: ./emp_app/build  # Ensure correct build output directory

    # Azure Logout
    - name: Azure Logout
      run: |
        az logout
